MODEL:
  META_ARCHITECTURE: "CustomRCNN"
  PROPOSAL_GENERATOR:
    NAME: "CenterNet"
  BACKBONE:
    NAME: "build_p37_dla_bifpn_backbone"
  WEIGHTS: ''
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.12, 57.375]
  BIFPN:
    OUT_CHANNELS: 160
    NUM_LEVELS: 5
    NUM_BIFPN: 3
  FPN:
    IN_FEATURES: ["dla3", "dla4", "dla5"]
  ROI_HEADS:
    NUM_CLASSES: 1
    SCORE_THRESH_TEST: 0.01
    NAME: CustomCascadeROIHeads
    IN_FEATURES: ["p3"]
    IOU_THRESHOLDS: [0.6]
    NMS_THRESH_TEST: 0.7
  ROI_BOX_CASCADE_HEAD:
    IOUS: [0.6, 0.7, 0.8]
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
    CLS_AGNOSTIC_BBOX_REG: True
    MULT_PROPOSAL_SCORE: True
  CENTERNET:
    NUM_CLASSES: 1
    REG_WEIGHT: 1.
    NOT_NORM_REG: True
    ONLY_PROPOSAL: True
    WITH_AGN_HM: True
    INFERENCE_TH: 0.0001
    PRE_NMS_TOPK_TRAIN: 4000
    POST_NMS_TOPK_TRAIN: 2000
    PRE_NMS_TOPK_TEST: 1000
    POST_NMS_TOPK_TEST: 128
    NMS_TH_TRAIN: 0.7
    NMS_TH_TEST: 0.6
    POS_WEIGHT: 0.5
    NEG_WEIGHT: 0.5
DATASETS:
  TRAIN: ("crowdhuman_amodal_train",)
  TEST: ("mot17_halfval",'crowdhuman_amodal_val')
TEST:
  DETECTIONS_PER_IMAGE: 100
  EVAL_PERIOD: 10000000
SOLVER:
  USE_CUSTOM_SOLVER: True
  OPTIMIZER: ADAMW
  BASE_LR: 0.0001
  MAX_ITER: 45000
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  IMS_PER_BATCH: 32
  CLIP_GRADIENTS:
    ENABLED: True
INPUT:
  FORMAT: RGB
  CUSTOM_AUG: EfficientDetResizeCrop
  TRAIN_SIZE: 896
  NOT_CLAMP_BOX: True
OUTPUT_DIR: "./output/GTR_MOT/auto"